language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - REQUIREMENTS=travis_wtf1.txt
  - REQUIREMENTS=travis_wtf2.txt

install: "pip install -r $REQUIREMENTS --use-mirrors"

services: mongodb

script: nosetests flask_admin/tests
