sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - WTFORMS_VERSION=1
  - WTFORMS_VERSION=2

addons:
  postgresql: "9.4"

services:
  - postgresql
  - mongodb

before_script:
  - psql -U postgres -c 'CREATE DATABASE flask_admin_test;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;' flask_admin_test
  - psql -U postgres -c 'CREATE EXTENSION hstore;' flask_admin_test

install:
  - pip install tox

script: tox -e py-WTForms$WTFORMS_VERSION

after_success:
    - coveralls
